package internal

// Code generated by gen. Do not edit!
// 代码由 gen 生成。不要手工编辑！

import (
	"proto/chat"

	"zeus/net/msgreg"
	"zeus/net/server"
)

func init() {
	// [ServerToClient] 注册发送的消息。需要从类型获取ID。
	msgreg.RegMsg2ID(&chat.ChatResponse{}, 10002)
	msgreg.RegMsg2ID(&chat.ChatMessage{}, 10003)
}

func RegMsgCreators_chat(svr _IRegMsgCreator) {
	// [ClientToServer] 注册接收的消息。需要从ID创建消息。
	svr.RegMsgCreator(10001, func() server.IMsg { return &chat.ChatRequest{} })
}
