package internal

// Code generated by gen. Do not edit!
// 代码由 gen 生成。不要手工编辑！

import (
	"msgdef/gensvr/proc"
	"proto/chat"

	"zeus/net/server"

	assert "github.com/aurelien-rainone/assertgo"
)

// Wrapper 是 Proc 的封装。
// Proc 由用户实现，其 MsgProc_MyMsg(msg *pb.MyMsg) 中的参数是具体的消息类。
// 封装后为 MsgProc_MyMsg(msg IMsg), 这个接口才能注册到服务器。
type Wrapper_chat struct {
	proc *proc.Proc_chat
}

// CloneAndRegisterMsgProcFunctions 克隆自身并注册消息处理函数.
func (w *Wrapper_chat) CloneAndRegisterMsgProcFunctions(sess server.ISession) {
	assert.True(sess != nil, "session is nil")
	result := &Wrapper_chat{
		proc: proc.NewProc_chat(sess),
	}

	sess.RegMsgProcFunc(10001, result.MsgProc_ChatRequest)

	sess.AddOnClosed(result.proc.OnClosed)
}

func (w *Wrapper_chat) MsgProc_ChatRequest(msg server.IMsg) {
	w.proc.MsgProc_ChatRequest(msg.(*chat.ChatRequest))
}
